# Generated by Django 4.1.2 on 2022-10-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_room_participants"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="participants",),
    ]
