# Generated by Django 4.1.2 on 2022-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_room_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="post_image",
            field=models.ImageField(null=True, upload_to="imgs"),
        ),
    ]
