# Generated by Django 4.1.2 on 2022-11-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="images"
            ),
        ),
    ]
