# Generated by Django 4.1.2 on 2022-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
