# Generated by Django 4.1.2 on 2022-11-05 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0015_room_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="likes",
            field=models.ManyToManyField(
                related_name="room_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
