# Generated by Django 4.1.2 on 2022-11-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_room_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="bio", field=models.TextField(blank=True),
        ),
    ]
