# Generated by Django 4.1.2 on 2022-11-05 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0017_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="follower",
            field=models.ManyToManyField(
                null=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
